# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_renv_wrappers", use_symbols = TRUE, package_name = "renv")

#' @usage NULL
#' @useDynLib renv, .registration = TRUE
NULL

acquire_lock_infallible <- function(file) .Call(wrap__acquire_lock_infallible, file)

lock_increment_ref_count <- function(lock) invisible(.Call(wrap__lock_increment_ref_count, lock))

release_lock <- function(lock) invisible(.Call(wrap__release_lock, lock))


# nolint end
